name: Farmwelt-Plugin
version: '${project.version}'
main: benkralex.farmwelt.Farmwelt
api-version: '1.20'
permissions:
  farm.create:
    default: op
  farm.tp:
    default: true
  farm.delete:
    default: op
commands:
  createfarmworld:
    description: "Erstellt neue Welten"
    usage: "/createfarmworld <Weltname> <Dimension> [true/false: private world]"
    aliases: "createfarm"
    permission: "farm.create"
  farmworld:
    description: "Teleportiert dich zu einer Welt"
    usage: "/farmworld <Weltname>"
    aliases: "farm"
    permission: "farm.tp"
  deletefarmworld:
    description: "Löscht eine Welt"
    usage: "/deletefarmworld"
    aliases: ["delfarm", "deletefarm"]
    permission: "farm.delete"