name: Farmwelt-Plugin
version: '1.0'
main: benkralex.farmwelt.Farmwelt
api-version: '1.20'
permissions:
  farmwelt.create:
    default: op
commands:
  createworld:
    description: "Erstellt neue Welten"
    usage: "/createworld <Weltname> <Dimension> [true/false: private world]"
    aliases: "cworld"
    permission: "farmwelt.create"