name: Farmwelt-Plugin
version: '2.0'
main: benkralex.farmwelt.Farmwelt
api-version: '1.20'
permissions:
  farm.create:
    default: op
  farm.tp:
    default: true
  farm.delete:
    default: op
commands:
  createfarmworld:
    description: "Erstellt neue Welten"
    usage: "/createfarmworld <Weltname> <Dimension> [true/false: private world]"
    permission: "farm.create"
  farmworld:
    description: "Teleportiert dich zu einer Welt"
    usage: "/farmworld <Weltname>"
    aliases: "farm"
    permission: "farm.tp"
  deletefarmworld:
    description: "Löscht eine Welt"
    usage: "/deletefarmworld <Weltname>"
    permission: "farm.delete"
  mainworld:
    description: "Teleportiert dich in die Oberwelt"
    usage: "/mainworld"
    permission: "farm.tp"